name: Build
on:
    pull_request:
    push:
        branches: [ master, dev ]
    workflow_dispatch:
permissions:
    statuses: write
    contents: read

jobs:
    build-linux-clang:
        name: Linux, Clang
        runs-on: ubuntu-latest
        env:
            CC: clang
            CXX: clang++
            CFLAGS: -Werror
            CXXFLAGS: -Werror

        steps:
            - uses: actions/checkout@v3

            - name: Configure static library
              run: cmake -S . -B build-static -D ENKITS_SANITIZE=ON -DENKITS_INSTALL=ON
            - name: Build static library
              run: cmake --build build-static --parallel
            - name: Test static library
              run: ./build-static/TestAll
            - name: Install static artifacts
              run: cmake --install build-static --prefix ${{ github.workspace }}/install-static
            - name: Setup examples using installed artifacts
              run: cmake -S example -B build-static-examples -D ENKITS_INSTALL_DIR=${{ github.workspace }}/install-static
            - name: Build examples
              run: cmake --build build-static-examples --parallel
            - name: Test examples
              run: ./build-static-examples/ParallelSum_c && ./build-static-examples/PinnedTask

            - name: Configure shared library
              run: cmake -S . -B build-shared -D ENKITS_BUILD_SHARED=ON -DENKITS_INSTALL=ON
            - name: Build shared library
              run: cmake --build build-shared --parallel
            - name: Test shared library
              run: ./build-shared/TestAll
            - name: Install shared artifacts
              run: cmake --install build-shared --prefix ${{ github.workspace }}/install-shared
            - name: Setup examples using installed artifacts
              run: cmake -S example -B build-shared-examples -D ENKITS_INSTALL_DIR=${{ github.workspace }}/install-shared
            - name: Build examples
              run: cmake --build build-shared-examples --parallel
            - name: Test examples
              run: ./build-shared-examples/ParallelSum_c && ./build-shared-examples/PinnedTask

    build-linux-gcc:
        name: Linux, gcc
        runs-on: ubuntu-latest
        env:
            CC: gcc
            CXX: g++
            CFLAGS: -Werror
            CXXFLAGS: -Werror

        steps:
            - uses: actions/checkout@v3

            - name: Configure static library
              run: cmake -S . -B build-static -D ENKITS_SANITIZE=ON -DENKITS_INSTALL=ON
            - name: Build static library
              run: cmake --build build-static --parallel
            - name: Test static library
              run: ./build-static/TestAll
            - name: Install static artifacts
              run: cmake --install build-static --prefix ${{ github.workspace }}/install-static
            - name: Setup examples using installed artifacts
              run: cmake -S example -B build-static-examples -D ENKITS_INSTALL_DIR=${{ github.workspace }}/install-static
            - name: Build examples
              run: cmake --build build-static-examples --parallel
            - name: Test examples
              run: ./build-static-examples/ParallelSum_c && ./build-static-examples/PinnedTask

            - name: Configure shared library
              run: cmake -S . -B build-shared -D ENKITS_BUILD_SHARED=ON -DENKITS_INSTALL=ON
            - name: Build shared library
              run: cmake --build build-shared --parallel
            - name: Test shared library
              run: ./build-shared/TestAll
            - name: Install shared artifacts
              run: cmake --install build-shared --prefix ${{ github.workspace }}/install-shared
            - name: Setup examples using installed artifacts
              run: cmake -S example -B build-shared-examples -D ENKITS_INSTALL_DIR=${{ github.workspace }}/install-shared
            - name: Build examples
              run: cmake --build build-shared-examples --parallel
            - name: Test examples
              run: ./build-shared-examples/ParallelSum_c && ./build-shared-examples/PinnedTask

    build-ubuntu-zig:
        name: Linux, zig
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: mlugg/setup-zig@v2
            with:
              version: 0.15.1

          - name: Build static library and priorities
            run: zig build -Dbuild_examples=true -Dshared=false -Dtask_priorities=4
          - name: Test static library
            run: ./zig-out/bin/TestAll

          - name: Build shared library
            run: zig build -Dbuild_examples=true -Dshared=true
          - name: Test shared library
            run: ./zig-out/bin/TestAll


    build-macos-cocoa-clang:
        name: Cocoa (macOS, Clang)
        runs-on: macos-latest
        env:
            CFLAGS: -Werror
            CXXFLAGS: -Werror
        steps:
            - uses: actions/checkout@v3

            - name: Configure static library
              run: cmake -S . -B build-static -D ENKITS_SANITIZE=ON -DENKITS_INSTALL=ON
            - name: Build static library
              run: cmake --build build-static --parallel
            - name: Test static library
              run: ./build-static/TestAll
            - name: Install static artifacts
              run: cmake --install build-static --prefix ${{ github.workspace }}/install-static
            - name: Setup examples using installed artifacts
              run: cmake -S example -B build-static-examples -D ENKITS_INSTALL_DIR=${{ github.workspace }}/install-static
            - name: Build examples
              run: cmake --build build-static-examples --parallel
            - name: Test examples
              run: ./build-static-examples/ParallelSum_c && ./build-static-examples/PinnedTask

            - name: Configure shared library
              run: cmake -S . -B build-shared -D ENKITS_BUILD_SHARED=ON -DENKITS_INSTALL=ON
            - name: Build shared library
              run: cmake --build build-shared --parallel
            - name: Test shared library
              run: ./build-shared/TestAll
            - name: Install shared artifacts
              run: cmake --install build-shared --prefix ${{ github.workspace }}/install-shared
            - name: Setup examples using installed artifacts
              run: cmake -S example -B build-shared-examples -D ENKITS_INSTALL_DIR=${{ github.workspace }}/install-shared
            - name: Build examples
              run: cmake --build build-shared-examples --parallel
            - name: Test examples
              run: ./build-shared-examples/ParallelSum_c && ./build-shared-examples/PinnedTask

    build-windows-win32-vs2022:
        name: Win32 (Windows, VS2022)
        runs-on: windows-latest
        env:
            CFLAGS: /WX
            CXXFLAGS: /WX
        steps:
            - uses: actions/checkout@v3

            - name: Setup MSVC dev command prompt
              uses: TheMrMilchmann/setup-msvc-dev@v3
              with:
                arch: x64

            - name: Configure static library
              run: cmake -S . -B build-static -G "Visual Studio 17 2022" -D ENKITS_SANITIZE=ON -DENKITS_INSTALL=ON
            - name: Build static library
              run: cmake --build build-static --parallel
            - name: Test static library
              run: .\build-static\Debug\TestAll.exe
            - name: Install static artifacts
              run: cmake --install build-static --prefix ${{ github.workspace }}/install-static
            - name: Setup examples using installed artifacts
              run: cmake -S example -B build-static-examples -D ENKITS_INSTALL_DIR=${{ github.workspace }}/install-static
            - name: Build examples
              run: cmake --build build-static-examples --parallel
            - name: Test examples
              run: .\build-static-examples\Debug\ParallelSum_c.exe && .\build-static-examples\Debug\PinnedTask.exe

            - name: Configure shared library
              run: cmake -S . -B build-shared -G "Visual Studio 17 2022" -D ENKITS_BUILD_SHARED=ON -DENKITS_INSTALL=ON
            - name: Build shared library
              run: cmake --build build-shared --parallel
            - name: Test shared library
              run: .\build-shared\Debug\TestAll.exe
            - name: Install shared artifacts
              run: cmake --install build-shared --prefix ${{ github.workspace }}/install-shared
            - name: Setup examples using installed artifacts
              run: cmake -S example -B build-shared-examples -D ENKITS_INSTALL_DIR=${{ github.workspace }}/install-shared
            - name: Build examples
              run: cmake --build build-shared-examples --parallel
            - name: Test examples
              run: .\build-shared-examples\Debug\ParallelSum_c.exe && .\build-shared-examples\Debug\PinnedTask.exe

    build-windows-win32-zig:
        name: Win32 (Windows, zig)
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v3
        - uses: mlugg/setup-zig@v2
          with:
            version: 0.15.1

        - name: Build static library and priorities
          run: zig build -Dbuild_examples=true -Dshared=false -Dtask_priorities=4
        - name: Test static library
          run: .\zig-out\bin\TestAll.exe

        - name: Build shared library
          run: zig build -Dbuild_examples=true -Dshared=true
        - name: Test shared library
          run: .\zig-out\bin\TestAll.exe
